/* Auto-generated by genmsg_cpp for file /home/jonkim93/catkin_ws/src/raven_pose_estimator/msg/IDandPoints.msg */
#ifndef RAVEN_POSE_ESTIMATOR_MESSAGE_IDANDPOINTS_H
#define RAVEN_POSE_ESTIMATOR_MESSAGE_IDANDPOINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"

namespace raven_pose_estimator
{
template <class ContainerAllocator>
struct IDandPoints_ {
  typedef IDandPoints_<ContainerAllocator> Type;

  IDandPoints_()
  : header()
  , ids()
  , points()
  {
  }

  IDandPoints_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , ids(_alloc)
  , points(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _ids_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  ids;

  typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  points;


  typedef boost::shared_ptr< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raven_pose_estimator::IDandPoints_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IDandPoints
typedef  ::raven_pose_estimator::IDandPoints_<std::allocator<void> > IDandPoints;

typedef boost::shared_ptr< ::raven_pose_estimator::IDandPoints> IDandPointsPtr;
typedef boost::shared_ptr< ::raven_pose_estimator::IDandPoints const> IDandPointsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::raven_pose_estimator::IDandPoints_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace raven_pose_estimator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raven_pose_estimator::IDandPoints_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4346c6c6950f817c3b20e8abb8c2bc3a";
  }

  static const char* value(const  ::raven_pose_estimator::IDandPoints_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4346c6c6950f817cULL;
  static const uint64_t static_value2 = 0x3b20e8abb8c2bc3aULL;
};

template<class ContainerAllocator>
struct DataType< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raven_pose_estimator/IDandPoints";
  }

  static const char* value(const  ::raven_pose_estimator::IDandPoints_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32[] ids\n\
geometry_msgs/Point[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::raven_pose_estimator::IDandPoints_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::raven_pose_estimator::IDandPoints_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.ids);
    stream.next(m.points);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IDandPoints_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raven_pose_estimator::IDandPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::raven_pose_estimator::IDandPoints_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVEN_POSE_ESTIMATOR_MESSAGE_IDANDPOINTS_H

