/* Auto-generated by genmsg_cpp for file /home/meg/catkin_ws/src/raven_pose_estimator/msg/JointsAndPoses.msg */
#ifndef RAVEN_POSE_ESTIMATOR_MESSAGE_JOINTSANDPOSES_H
#define RAVEN_POSE_ESTIMATOR_MESSAGE_JOINTSANDPOSES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "std_msgs/String.h"
#include "geometry_msgs/Pose.h"

namespace raven_pose_estimator
{
template <class ContainerAllocator>
struct JointsAndPoses_ {
  typedef JointsAndPoses_<ContainerAllocator> Type;

  JointsAndPoses_()
  : header()
  , joints()
  , poses()
  {
  }

  JointsAndPoses_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , joints(_alloc)
  , poses(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _joints_type;
  std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  joints;

  typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _poses_type;
  std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  poses;


  typedef boost::shared_ptr< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointsAndPoses
typedef  ::raven_pose_estimator::JointsAndPoses_<std::allocator<void> > JointsAndPoses;

typedef boost::shared_ptr< ::raven_pose_estimator::JointsAndPoses> JointsAndPosesPtr;
typedef boost::shared_ptr< ::raven_pose_estimator::JointsAndPoses const> JointsAndPosesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace raven_pose_estimator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "940bac79fe18726ba8a192c18ef68290";
  }

  static const char* value(const  ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x940bac79fe18726bULL;
  static const uint64_t static_value2 = 0xa8a192c18ef68290ULL;
};

template<class ContainerAllocator>
struct DataType< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "raven_pose_estimator/JointsAndPoses";
  }

  static const char* value(const  ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
std_msgs/String[] joints\n\
geometry_msgs/Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.joints);
    stream.next(m.poses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointsAndPoses_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::raven_pose_estimator::JointsAndPoses_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVEN_POSE_ESTIMATOR_MESSAGE_JOINTSANDPOSES_H

