(cl:defpackage stereo_click-srv
  (:use )
  (:export
   "CONVERTPOINT"
   "<CONVERTPOINT-REQUEST>"
   "CONVERTPOINT-REQUEST"
   "<CONVERTPOINT-RESPONSE>"
   "CONVERTPOINT-RESPONSE"
   "CONVERTPOINTS"
   "<CONVERTPOINTS-REQUEST>"
   "CONVERTPOINTS-REQUEST"
   "<CONVERTPOINTS-RESPONSE>"
   "CONVERTPOINTS-RESPONSE"
  ))

