/* Auto-generated by genmsg_cpp for file /home/jonathankim/fuerte_workspace/sandbox/image_processing_packages/stereo_click/srv/ConvertPoint.srv */
#ifndef STEREO_CLICK_SERVICE_CONVERTPOINT_H
#define STEREO_CLICK_SERVICE_CONVERTPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "stereo_click/ClickPoint.h"


#include "geometry_msgs/PointStamped.h"

namespace stereo_click
{
template <class ContainerAllocator>
struct ConvertPointRequest_ {
  typedef ConvertPointRequest_<ContainerAllocator> Type;

  ConvertPointRequest_()
  : click_point()
  {
  }

  ConvertPointRequest_(const ContainerAllocator& _alloc)
  : click_point(_alloc)
  {
  }

  typedef  ::stereo_click::ClickPoint_<ContainerAllocator>  _click_point_type;
   ::stereo_click::ClickPoint_<ContainerAllocator>  click_point;


  typedef boost::shared_ptr< ::stereo_click::ConvertPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stereo_click::ConvertPointRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ConvertPointRequest
typedef  ::stereo_click::ConvertPointRequest_<std::allocator<void> > ConvertPointRequest;

typedef boost::shared_ptr< ::stereo_click::ConvertPointRequest> ConvertPointRequestPtr;
typedef boost::shared_ptr< ::stereo_click::ConvertPointRequest const> ConvertPointRequestConstPtr;


template <class ContainerAllocator>
struct ConvertPointResponse_ {
  typedef ConvertPointResponse_<ContainerAllocator> Type;

  ConvertPointResponse_()
  : pt3d()
  {
  }

  ConvertPointResponse_(const ContainerAllocator& _alloc)
  : pt3d(_alloc)
  {
  }

  typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _pt3d_type;
   ::geometry_msgs::PointStamped_<ContainerAllocator>  pt3d;


  typedef boost::shared_ptr< ::stereo_click::ConvertPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stereo_click::ConvertPointResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ConvertPointResponse
typedef  ::stereo_click::ConvertPointResponse_<std::allocator<void> > ConvertPointResponse;

typedef boost::shared_ptr< ::stereo_click::ConvertPointResponse> ConvertPointResponsePtr;
typedef boost::shared_ptr< ::stereo_click::ConvertPointResponse const> ConvertPointResponseConstPtr;

struct ConvertPoint
{

typedef ConvertPointRequest Request;
typedef ConvertPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ConvertPoint
} // namespace stereo_click

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::stereo_click::ConvertPointRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::stereo_click::ConvertPointRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::stereo_click::ConvertPointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "12f3d3a572dc872a5cf394c061886880";
  }

  static const char* value(const  ::stereo_click::ConvertPointRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x12f3d3a572dc872aULL;
  static const uint64_t static_value2 = 0x5cf394c061886880ULL;
};

template<class ContainerAllocator>
struct DataType< ::stereo_click::ConvertPointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_click/ConvertPointRequest";
  }

  static const char* value(const  ::stereo_click::ConvertPointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::stereo_click::ConvertPointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_click/ClickPoint click_point\n\
\n\
================================================================================\n\
MSG: stereo_click/ClickPoint\n\
float32 x\n\
float32 y\n\
sensor_msgs/CameraInfo camera_info\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/CameraInfo\n\
# This message defines meta information for a camera. It should be in a\n\
# camera namespace on topic \"camera_info\" and accompanied by up to five\n\
# image topics named:\n\
#\n\
#   image_raw - raw data from the camera driver, possibly Bayer encoded\n\
#   image            - monochrome, distorted\n\
#   image_color      - color, distorted\n\
#   image_rect       - monochrome, rectified\n\
#   image_rect_color - color, rectified\n\
#\n\
# The image_pipeline contains packages (image_proc, stereo_image_proc)\n\
# for producing the four processed image topics from image_raw and\n\
# camera_info. The meaning of the camera parameters are described in\n\
# detail at http://www.ros.org/wiki/image_pipeline/CameraInfo.\n\
#\n\
# The image_geometry package provides a user-friendly interface to\n\
# common operations using this meta information. If you want to, e.g.,\n\
# project a 3d point into image coordinates, we strongly recommend\n\
# using image_geometry.\n\
#\n\
# If the camera is uncalibrated, the matrices D, K, R, P should be left\n\
# zeroed out. In particular, clients may assume that K[0] == 0.0\n\
# indicates an uncalibrated camera.\n\
\n\
#######################################################################\n\
#                     Image acquisition info                          #\n\
#######################################################################\n\
\n\
# Time of image acquisition, camera coordinate frame ID\n\
Header header    # Header timestamp should be acquisition time of image\n\
                 # Header frame_id should be optical frame of camera\n\
                 # origin of frame should be optical center of camera\n\
                 # +x should point to the right in the image\n\
                 # +y should point down in the image\n\
                 # +z should point into the plane of the image\n\
\n\
\n\
#######################################################################\n\
#                      Calibration Parameters                         #\n\
#######################################################################\n\
# These are fixed during camera calibration. Their values will be the #\n\
# same in all messages until the camera is recalibrated. Note that    #\n\
# self-calibrating systems may \"recalibrate\" frequently.              #\n\
#                                                                     #\n\
# The internal parameters can be used to warp a raw (distorted) image #\n\
# to:                                                                 #\n\
#   1. An undistorted image (requires D and K)                        #\n\
#   2. A rectified image (requires D, K, R)                           #\n\
# The projection matrix P projects 3D points into the rectified image.#\n\
#######################################################################\n\
\n\
# The image dimensions with which the camera was calibrated. Normally\n\
# this will be the full camera resolution in pixels.\n\
uint32 height\n\
uint32 width\n\
\n\
# The distortion model used. Supported models are listed in\n\
# sensor_msgs/distortion_models.h. For most cameras, \"plumb_bob\" - a\n\
# simple model of radial and tangential distortion - is sufficent.\n\
string distortion_model\n\
\n\
# The distortion parameters, size depending on the distortion model.\n\
# For \"plumb_bob\", the 5 parameters are: (k1, k2, t1, t2, k3).\n\
float64[] D\n\
\n\
# Intrinsic camera matrix for the raw (distorted) images.\n\
#     [fx  0 cx]\n\
# K = [ 0 fy cy]\n\
#     [ 0  0  1]\n\
# Projects 3D points in the camera coordinate frame to 2D pixel\n\
# coordinates using the focal lengths (fx, fy) and principal point\n\
# (cx, cy).\n\
float64[9]  K # 3x3 row-major matrix\n\
\n\
# Rectification matrix (stereo cameras only)\n\
# A rotation matrix aligning the camera coordinate system to the ideal\n\
# stereo image plane so that epipolar lines in both stereo images are\n\
# parallel.\n\
float64[9]  R # 3x3 row-major matrix\n\
\n\
# Projection/camera matrix\n\
#     [fx'  0  cx' Tx]\n\
# P = [ 0  fy' cy' Ty]\n\
#     [ 0   0   1   0]\n\
# By convention, this matrix specifies the intrinsic (camera) matrix\n\
#  of the processed (rectified) image. That is, the left 3x3 portion\n\
#  is the normal camera intrinsic matrix for the rectified image.\n\
# It projects 3D points in the camera coordinate frame to 2D pixel\n\
#  coordinates using the focal lengths (fx', fy') and principal point\n\
#  (cx', cy') - these may differ from the values in K.\n\
# For monocular cameras, Tx = Ty = 0. Normally, monocular cameras will\n\
#  also have R = the identity and P[1:3,1:3] = K.\n\
# For a stereo pair, the fourth column [Tx Ty 0]' is related to the\n\
#  position of the optical center of the second camera in the first\n\
#  camera's frame. We assume Tz = 0 so both cameras are in the same\n\
#  stereo image plane. The first camera always has Tx = Ty = 0. For\n\
#  the right (second) camera of a horizontal stereo pair, Ty = 0 and\n\
#  Tx = -fx' * B, where B is the baseline between the cameras.\n\
# Given a 3D point [X Y Z]', the projection (x, y) of the point onto\n\
#  the rectified image is given by:\n\
#  [u v w]' = P * [X Y Z 1]'\n\
#         x = u / w\n\
#         y = v / w\n\
#  This holds for both images of a stereo pair.\n\
float64[12] P # 3x4 row-major matrix\n\
\n\
\n\
#######################################################################\n\
#                      Operational Parameters                         #\n\
#######################################################################\n\
# These define the image region actually captured by the camera       #\n\
# driver. Although they affect the geometry of the output image, they #\n\
# may be changed freely without recalibrating the camera.             #\n\
#######################################################################\n\
\n\
# Binning refers here to any camera setting which combines rectangular\n\
#  neighborhoods of pixels into larger \"super-pixels.\" It reduces the\n\
#  resolution of the output image to\n\
#  (width / binning_x) x (height / binning_y).\n\
# The default values binning_x = binning_y = 0 is considered the same\n\
#  as binning_x = binning_y = 1 (no subsampling).\n\
uint32 binning_x\n\
uint32 binning_y\n\
\n\
# Region of interest (subwindow of full camera resolution), given in\n\
#  full resolution (unbinned) image coordinates. A particular ROI\n\
#  always denotes the same window of pixels on the camera sensor,\n\
#  regardless of binning settings.\n\
# The default setting of roi (all values 0) is considered the same as\n\
#  full resolution (roi.width = width, roi.height = height).\n\
RegionOfInterest roi\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/RegionOfInterest\n\
# This message is used to specify a region of interest within an image.\n\
#\n\
# When used to specify the ROI setting of the camera when the image was\n\
# taken, the height and width fields should either match the height and\n\
# width fields for the associated image; or height = width = 0\n\
# indicates that the full resolution image was captured.\n\
\n\
uint32 x_offset  # Leftmost pixel of the ROI\n\
                 # (0 if the ROI includes the left edge of the image)\n\
uint32 y_offset  # Topmost pixel of the ROI\n\
                 # (0 if the ROI includes the top edge of the image)\n\
uint32 height    # Height of ROI\n\
uint32 width     # Width of ROI\n\
\n\
# True if a distinct rectified ROI should be calculated from the \"raw\"\n\
# ROI in this message. Typically this should be False if the full image\n\
# is captured (ROI not used), and True if a subwindow is captured (ROI\n\
# used).\n\
bool do_rectify\n\
\n\
";
  }

  static const char* value(const  ::stereo_click::ConvertPointRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::stereo_click::ConvertPointResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::stereo_click::ConvertPointResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::stereo_click::ConvertPointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d7d33455780078c26d7ebd8e36150846";
  }

  static const char* value(const  ::stereo_click::ConvertPointResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd7d33455780078c2ULL;
  static const uint64_t static_value2 = 0x6d7ebd8e36150846ULL;
};

template<class ContainerAllocator>
struct DataType< ::stereo_click::ConvertPointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_click/ConvertPointResponse";
  }

  static const char* value(const  ::stereo_click::ConvertPointResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::stereo_click::ConvertPointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PointStamped pt3d\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::stereo_click::ConvertPointResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::stereo_click::ConvertPointRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.click_point);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ConvertPointRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::stereo_click::ConvertPointResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pt3d);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ConvertPointResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<stereo_click::ConvertPoint> {
  static const char* value() 
  {
    return "2ccb15871e57392cb262c1d7ec97e26a";
  }

  static const char* value(const stereo_click::ConvertPoint&) { return value(); } 
};

template<>
struct DataType<stereo_click::ConvertPoint> {
  static const char* value() 
  {
    return "stereo_click/ConvertPoint";
  }

  static const char* value(const stereo_click::ConvertPoint&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<stereo_click::ConvertPointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2ccb15871e57392cb262c1d7ec97e26a";
  }

  static const char* value(const stereo_click::ConvertPointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<stereo_click::ConvertPointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_click/ConvertPoint";
  }

  static const char* value(const stereo_click::ConvertPointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<stereo_click::ConvertPointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2ccb15871e57392cb262c1d7ec97e26a";
  }

  static const char* value(const stereo_click::ConvertPointResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<stereo_click::ConvertPointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_click/ConvertPoint";
  }

  static const char* value(const stereo_click::ConvertPointResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // STEREO_CLICK_SERVICE_CONVERTPOINT_H

